### PR TITLE
Adding Quickeys

### PR DESCRIPTION
**Pull request by alexrosenfeld10**
Adding my application Quickeys to the list of apps.

## Project URL

https://github.com/alexrosenfeld10/Quickeys

## Category

Menu bar applications

## Description

 Not much to describe, just added the entry to the `README.md` as per instructions.

## Why it should be included to `Awesome macOS open source applications ` (optional)
I haven't found any apps that accomplish the same functionality.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in alphabetical order
- [x] Appropriate language icon(s) added if applicable
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
@alexrosenfeld10 Thanks for your contribution!

**Comment by alexrosenfeld10** [comment]
Thanks for adding!

**Comment by serhii-londar** [comment]
@alexrosenfeld10 One small suggestion: Add screenshots of your app to Readme.md file.

**Comment by alexrosenfeld10** [comment]
Thanks for the suggestion, will do.

**Comment by serhii-londar** [comment]
:+1

**Comment by alexrosenfeld10** [comment]
Added! 👍

**Pull request merged**
