### PR TITLE
Add ChefInspector

### PR DESCRIPTION
**Pull request by Yasumoto**
## Project URL
https://github.com/Yasumoto/ChefInspector

## Category
Development -> Other

## Description
Add an application for querying your Chef Server (both nodes and their attributes).
 
## Why it should be included to `Awesome macOS open source applications `
A good DevOps-y application for macOS.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Appropriate language icon(s) added if applicable
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
@Yasumoto Can you create better Readme file? It is have no information about application.

**Comment by serhii-londar** [comment]
Closed due to no activity.

**Comment by Yasumoto** [comment]
Howdy @serhii-londar! Thanks for the nudge, I updated the README and pushed some improvements. If you have other suggestions please let me know! 🙇

**Comment by serhii-londar** [comment]
Hi, @Yasumoto I think it would be better to open new PR.

**Pull request closed without merging**
