### PR TITLE
Add pomodoro cycle app

### PR DESCRIPTION
**Pull request by jet8a**
## Project URL
https://github.com/jet8a/pomodoro-cycle-app

## Category
Productivity

## Description
Pomodoro cycle tracker

## Checklist

- [x] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x] Only one project/change is in this pull request
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
7650 | [302](https://httpstatuses.com/302) | https://github.com/jet8a/pomodoro-cycle-app/raw/master/src/favicon.png?raw=true redirects to<br>https://raw.githubusercontent.com/jet8a/pomodoro-cycle-app/master/src/favicon.png
7652 | [302](https://httpstatuses.com/302) | https://github.com/jet8a/pomodoro-cycle-app/raw/master/screenshots/1.png?raw=true redirects to<br>https://raw.githubusercontent.com/jet8a/pomodoro-cycle-app/master/screenshots/1.png


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jet8a** [comment]
What do I need to fix?

**Comment by serhii-londar** [comment]
@jet8a Thank you! 👍

**Comment by jet8a** [comment]
@serhii-londar I can't see the app here https://github.com/serhii-londar/open-source-mac-os-apps#productivity

**Pull request merged**
