### PR TITLE
Add CoreLocationCLI

### PR DESCRIPTION
**Pull request by fulldecent**
## Project URL
CoreLocationCLI

## Category
Utility

## Description
CoreLocationCLI gets the physical location of your device and prints it to standard output. If you move it can also print your updated location.
 
## Why it should be included to `Awesome macOS open source applications ` (optional)
In case you forget where you are.

## Checklist
- [x] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x] Only one project/change is in this pull request
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
7827 | Dupe | https://github.com/fulldecent/corelocationcli 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by fulldecent** [comment]
Thank you, other PR got in

**Comment by fulldecent** [comment]
Undo. Maybe that note was not duplicate.

**Comment by serhii-londar** [comment]
@fulldecent Thank you! 👍

**Pull request merged**
