### PR TITLE
Update READE's language icons #572

### PR DESCRIPTION
**Pull request by KKWANH**
# Icon Design Change for README
Changed language icon designs from the simple list to the badge form.

## Checklist

- [ ] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x] Only one project/change is in this pull request
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by suliveevil** [comment]
Objective-C link broken, should be:
```text
https://img.shields.io/badge/Objective%20C-424242?style=for-the-badge&logo=C&logoColor=white
```

**Comment by KKWANH** [comment]
> Objective-C link broken, should be:
> 
> ```
> https://img.shields.io/badge/Objective%20C-424242?style=for-the-badge&logo=C&logoColor=white
> ```

I updated it! Thank you.

**Comment by KKWANH** [comment]
hello, @suliveevil, I am participating at hacktoberfest and it's time limit is 10/21. Can you review/merge my commit? Thank you.

**Comment by suliveevil** [comment]
I have no authority over this repo. 😅

**Comment by KKWANH** [comment]
> I have no authority over this repo. 😅

sorry... could you help me who do i have to tag for this?

**Review by serhii-londar — APPROVED** [review]

**Comment by serhii-londar** [comment]
@KKWANH Thank you ❤️

**Pull request merged**
