### PR TITLE
added Syncalicious project

### PR DESCRIPTION
**Pull request by skywinder**
✅

### CODE REVIEW

**Comment by serhii-londar** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 329 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2169 | [301](https://httpstatuses.com/301) | https://httptoolkit.tech/mock/ redirects to<br>https://httptoolkit.tech/
2654 | [429](https://httpstatuses.com/429) | https://github.com/textmate/textmate 
2670 | [429](https://httpstatuses.com/429) | https://github.com/qvacua/vimr 
2684 | [429](https://httpstatuses.com/429) | https://github.com/Capevace/BetterPiP 
2700 | [429](https://httpstatuses.com/429) | https://github.com/arnoappenzeller/PiPifier 
2718 | [429](https://httpstatuses.com/429) | https://github.com/bfmatei/PiPTool 
2732 | [429](https://httpstatuses.com/429) | https://github.com/bow-swift/nef-plugin 
2749 | [429](https://httpstatuses.com/429) | https://github.com/Clipy/Clipy 
2766 | [429](https://httpstatuses.com/429) | https://github.com/hluk/CopyQ 
2782 | [429](https://httpstatuses.com/429) | https://github.com/onmyway133/FinderGo 
2796 | [429](https://httpstatuses.com/429) | https://github.com/Mortennn/FiScript 
2813 | [429](https://httpstatuses.com/429) | https://github.com/sozercan/OpenInCode 
2829 | [429](https://httpstatuses.com/429) | https://github.com/wesnoth/wesnoth 
2843 | [429](https://httpstatuses.com/429) | https://github.com/alunbestor/Boxer 
2858 | [429](https://httpstatuses.com/429) | https://github.com/dolphin-emu/dolphin 
2872 | [429](https://httpstatuses.com/429) | https://github.com/OpenEmu/OpenEmu 
2888 | [429](https://httpstatuses.com/429) | https://github.com/OpenRCT2/OpenRCT2 
2904 | [429](https://httpstatuses.com/429) | https://github.com/AaronRandall/Screentendo 
2920 | [429](https://httpstatuses.com/429) | https://github.com/daylen/stockfish-mac 
2935 | [429](https://httpstatuses.com/429) | https://github.com/aseprite/aseprite 
2950 | [429](https://httpstatuses.com/429) | https://github.com/gragrance/CaptuocrToy 
2966 | [429](https://httpstatuses.com/429) | https://github.com/onmyway133/GifCapture 
2986 | [429](https://httpstatuses.com/429) | https://github.com/lettier/gifcurry 
3003 | [429](https://httpstatuses.com/429) | https://github.com/sindresorhus/Gifski 
3022 | [429](https://httpstatuses.com/429) | https://github.com/CleanCocoa/InfiniteCanvas 
3038 | [429](https://httpstatuses.com/429) | https://github.com/dsward2/macSVG 
3054 | [429](https://httpstatuses.com/429) | https://github.com/BafS/Material-Colors-native 
3070 | [429](https://httpstatuses.com/429) | https://github.com/pencil2d/pencil 
3084 | [429](https://httpstatuses.com/429) | https://github.com/duyquoc/ScreenToLayers 
3101 | [429](https://httpstatuses.com/429) | https://github.com/atom/atom 
3115 | [429](https://httpstatuses.com/429) | https://github.com/onivim/oni 
3130 | [429](https://httpstatuses.com/429) | https://github.com/Microsoft/vscode 
3146 | [429](https://httpstatuses.com/429) | https://github.com/pkulchenko/ZeroBraneStudio 
3162 | [429](https://httpstatuses.com/429) | https://github.com/shgodoroja/APNGb 
3176 | [429](https://httpstatuses.com/429) | https://github.com/szTheory/exifcleaner 
3194 | [429](https://httpstatuses.com/429) | https://github.com/chrissimpkins/Crunch 
3208 | [429](https://httpstatuses.com/429) | https://github.com/wddwycc/Freehand 
3224 | [429](https://httpstatuses.com/429) | https://github.com/GNOME/gimp 
3238 | [429](https://httpstatuses.com/429) | https://github.com/liamrosenfeld/Iconology 
3252 | [429](https://httpstatuses.com/429) | https://github.com/kornelski/ImageAlpha 
3269 | [429](https://httpstatuses.com/429) | https://github.com/meowtec/Imagine 
3283 | [429](https://httpstatuses.com/429) | https://github.com/bluegill/katana 
3298 | [429](https://httpstatuses.com/429) | https://github.com/gergelysanta/photominer 
3319 | [429](https://httpstatuses.com/429) | https://github.com/crilleengvall/Screenbar 
3335 | [429](https://httpstatuses.com/429) | https://github.com/1000ch/WebPonize 
3350 | [429](https://httpstatuses.com/429) | https://github.com/msvisser/AnnePro-mac 
3364 | [429](https://httpstatuses.com/429) | https://github.com/Pyroh/Fluor 
3378 | [429](https://httpstatuses.com/429) | https://github.com/yqrashawn/GokuRakuJoudo 
3392 | [429](https://httpstatuses.com/429) | https://github.com/tekezo/Karabiner 
3407 | [429](https://httpstatuses.com/429) | https://github.com/pqrs-org/Karabiner-Elements 
3422 | [429](https://httpstatuses.com/429) | https://github.com/utatti/kawa 
3439 | [429](https://httpstatuses.com/429) | https://github.com/gbammc/Thor 
3456 | [429](https://httpstatuses.com/429) | https://github.com/aahung/Unshaky 
3460 | [429](https://httpstatuses.com/429) | https://github.com/aahung/Unshaky/blob/master/README/menubar.png 
3461 | [429](https://httpstatuses.com/429) | https://github.com/aahung/Unshaky/blob/master/README/how-unshaky-works.png 
3473 | [429](https://httpstatuses.com/429) | https://github.com/amitmerchant1990/correo 
3487 | [429](https://httpstatuses.com/429) | https://github.com/dinhviethoa/dejalu 
3504 | [429](https://httpstatuses.com/429) | https://github.com/Foundry376/Mailspring 
3518 | [429](https://httpstatuses.com/429) | https://github.com/ramboxapp/community-edition 
3534 | [429](https://httpstatuses.com/429) | https://github.com/invesalius/invesalius3/ 
3552 | [429](https://httpstatuses.com/429) | https://github.com/alvesjtiago/airpass 
3566 | [429](https://httpstatuses.com/429) | https://github.com/tonsky/AnyBar 
3580 | [429](https://httpstatuses.com/429) | https://github.com/matryer/bitbar 
3594 | [429](https://httpstatuses.com/429) | https://github.com/josh-/CloudyTabs 
3610 | [429](https://httpstatuses.com/429) | https://github.com/inderdhir/DatWeatherDoe 
3624 | [429](https://httpstatuses.com/429) | https://github.com/Kwpolska/DisplayMenu 
3638 | [429](https://httpstatuses.com/429) | https://github.com/CodySchrank/gSwitch 
3652 | [429](https://httpstatuses.com/429) | https://github.com/iglance/iGlance 
3666 | [429](https://httpstatuses.com/429) | https://github.com/turkenh/KubeContext 
3683 | [429](https://httpstatuses.com/429) | https://github.com/lucasbento/menubar-brightness 
3697 | [429](https://httpstatuses.com/429) | https://github.com/yujitach/MenuMeters 
3711 | [429](https://httpstatuses.com/429) | https://github.com/isaiasmatewos/night-shift-control 
3727 | [429](https://httpstatuses.com/429) | https://github.com/nikhilsh/PSIBar 
3741 | [429](https://httpstatuses.com/429) | https://github.com/alexrosenfeld10/Quickeys 
3757 | [429](https://httpstatuses.com/429) | https://github.com/archagon/sensible-side-buttons 
3772 | [429](https://httpstatuses.com/429) | https://github.com/thompsonate/Shifty 
3788 | [429](https://httpstatuses.com/429) | https://github.com/AnaghSharma/Carol 
3802 | [429](https://httpstatuses.com/429) | https://github.com/cemolcay/ChordDetector 
3816 | [429](https://httpstatuses.com/429) | https://github.com/imanel/deezplayer 
3830 | [429](https://httpstatuses.com/429) | https://github.com/Zac-Garby/iTunes-Graphs 
3847 | [429](https://httpstatuses.com/429) | https://github.com/mamal72/lyricsify-mac 
3864 | [429](https://httpstatuses.com/429) | https://github.com/salomvary/soundcleod 
3880 | [429](https://httpstatuses.com/429) | https://github.com/ersel/spotify-cli-mac 
3896 | [429](https://httpstatuses.com/429) | https://github.com/steve228uk/YouTube-Music 
3915 | [429](https://httpstatuses.com/429) | https://github.com/ngquerol/Diurna 
3931 | [429](https://httpstatuses.com/429) | https://github.com/jingweno/hacker-menu 
3947 | [429](https://httpstatuses.com/429) | https://github.com/Ranchero-Software/NetNewsWire 
3961 | [429](https://httpstatuses.com/429) | https://github.com/ViennaRSS/vienna-rss 
3975 | [429](https://httpstatuses.com/429) | https://github.com/BoostIO/Boostnote 
3991 | [429](https://httpstatuses.com/429) | https://github.com/Kilian/fromscratch 
4006 | [429](https://httpstatuses.com/429) | https://github.com/glushchenko/fsnotes 
4023 | [429](https://httpstatuses.com/429) | https://github.com/laurent22/joplin 
4037 | [429](https://httpstatuses.com/429) | https://github.com/tuxu/nbviewer-app 
4051 | [429](https://httpstatuses.com/429) | https://github.com/jmcfarlane/notable 
4073 | [429](https://httpstatuses.com/429) | https://github.com/SauvageP/Notes 
4087 | [429](https://httpstatuses.com/429) | https://github.com/insidegui/NoteTaker 
4103 | [429](https://httpstatuses.com/429) | https://github.com/Automattic/simplenote-macos 
4119 | [429](https://httpstatuses.com/429) | https://github.com/standardnotes/web 
4136 | [429](https://httpstatuses.com/429) | https://github.com/buddax2/tmpNote 
4152 | [429](https://httpstatuses.com/429) | https://github.com/klaussinani/tusk 
4169 | [429](https://httpstatuses.com/429) | https://github.com/pbek/QOwnNotes 
4185 | [429](https://httpstatuses.com/429) | https://github.com/brunophilipe/Cakebrew 
4201 | [429](https://httpstatuses.com/429) | https://github.com/dteoh/devdocs-macos 
4217 | [429](https://httpstatuses.com/429) | https://github.com/2ndalpha/gasmask 
4231 | [429](https://httpstatuses.com/429) | https://github.com/specialunderwear/Hosts.prefpane 
4245 | [429](https://httpstatuses.com/429) | https://github.com/ImageOptim/ImageOptim 
4259 | [429](https://httpstatuses.com/429) | https://github.com/insidegui/KeyframesPlayer 
4275 | [429](https://httpstatuses.com/429) | https://github.com/hackjutsu/Lepton 
4289 | [429](https://httpstatuses.com/429) | https://github.com/Bunn/macGist 
4303 | [429](https://httpstatuses.com/429) | https://github.com/sveinbjornt/Platypus 
4317 | [429](https://httpstatuses.com/429) | https://github.com/goktugyil/QorumLogs 
4331 | [429](https://httpstatuses.com/429) | https://github.com/jhen0409/react-native-debugger 
4347 | [429](https://httpstatuses.com/429) | https://github.com/infinitered/reactotron 
4361 | [429](https://httpstatuses.com/429) | https://github.com/woofwoofinc/rktmachine 
4378 | [429](https://httpstatuses.com/429) | https://github.com/gosu/ruby-app 
4392 | [429](https://httpstatuses.com/429) | https://github.com/fitztrev/shuttle 
4408 | [429](https://httpstatuses.com/429) | https://github.com/SwiftyBeaver/SwiftyBeaver 
4422 | [429](https://httpstatuses.com/429) | https://github.com/swiftyapp/swifty 
4439 | [429](https://httpstatuses.com/429) | https://github.com/syncthing/syncthing-macos 
4455 | [429](https://httpstatuses.com/429) | https://github.com/jeffhodnett/Unused 
4469 | [429](https://httpstatuses.com/429) | https://github.com/lanayotech/vagrant-manager 
4485 | [429](https://httpstatuses.com/429) | https://github.com/z-------------/CPod 
4501 | [429](https://httpstatuses.com/429) | https://github.com/muammar/mkchromecast 
4515 | [429](https://httpstatuses.com/429) | https://github.com/insidegui/PodcastMenu 
4529 | [429](https://httpstatuses.com/429) | https://github.com/phranck/podlive-macos 
4541 | [429](https://httpstatuses.com/429) | https://github.com/dyerc/Doughnut 
4561 | [429](https://httpstatuses.com/429) | https://github.com/klaussinani/ao 
4585 | [429](https://httpstatuses.com/429) | https://github.com/KELiON/cerebro 
4599 | [429](https://httpstatuses.com/429) | https://github.com/naotaka/ClipMenu 
4615 | [429](https://httpstatuses.com/429) | https://github.com/n0shake/Clocker 
4629 | [429](https://httpstatuses.com/429) | https://github.com/dustinrue/ControlPlane 
4643 | [429](https://httpstatuses.com/429) | https://github.com/TermiT/flycut 
4657 | [429](https://httpstatuses.com/429) | https://github.com/federico-terzi/espanso 
4673 | [429](https://httpstatuses.com/429) | https://github.com/Clipy/KeyHolder 
4687 | [429](https://httpstatuses.com/429) | https://github.com/kiwix/apple 
4701 | [429](https://httpstatuses.com/429) | https://github.com/fespinoza/LinkedIdeas 
4717 | [429](https://httpstatuses.com/429) | https://github.com/p0deje/Maccy 
4733 | [429](https://httpstatuses.com/429) | https://github.com/shubhambatra3019/macOrganizer 
4747 | [429](https://httpstatuses.com/429) | https://github.com/hql287/Manta 
4761 | [429](https://httpstatuses.com/429) | https://github.com/thomasbrueggemann/paperless-desktop 
4778 | [429](https://httpstatuses.com/429) | https://github.com/PDF-Archiver/PDF-Archiver 
4794 | [429](https://httpstatuses.com/429) | https://github.com/quicksilver/Quicksilver 
4808 | [429](https://httpstatuses.com/429) | https://github.com/quickwords/quickwords 
4825 | [429](https://httpstatuses.com/429) | https://github.com/SelfControlApp/selfcontrol 
4839 | [429](https://httpstatuses.com/429) | https://github.com/Onix-Systems/osx-status-bar-todo 
4855 | [429](https://httpstatuses.com/429) | https://github.com/hovancik/stretchly 
4869 | [429](https://httpstatuses.com/429) | https://github.com/joaomoreno/thyme 
4883 | [429](https://httpstatuses.com/429) | https://github.com/michaelvillar/timer-app 
4913 | [429](https://httpstatuses.com/429) | https://github.com/jlong/TrelloApp 
4927 | [429](https://httpstatuses.com/429) | https://github.com/TailorDev/Watson 
4944 | [429](https://httpstatuses.com/429) | https://github.com/1000ch/whale 
4960 | [429](https://httpstatuses.com/429) | https://github.com/sendyhalim/Yomu 
4974 | [429](https://httpstatuses.com/429) | https://github.com/JohnCoates/Aerial 
4995 | [429](https://httpstatuses.com/429) | https://github.com/ved62/Image-As-Wallpaper 
5009 | [429](https://httpstatuses.com/429) | https://github.com/leonspok/Irvue-Screensaver 
5027 | [429](https://httpstatuses.com/429) | https://github.com/docterd/MusaicFM 
5043 | [429](https://httpstatuses.com/429) | https://github.com/winterbe/github-matrix-screensaver 
5060 | [429](https://httpstatuses.com/429) | https://github.com/objective-see/LuLu 
5074 | [429](https://httpstatuses.com/429) | https://github.com/alichtman/stronghold 
5105 | [429](https://httpstatuses.com/429) | https://github.com/mileswd/mac2imgur 
5119 | [429](https://httpstatuses.com/429) | https://github.com/nitroshare/nitroshare-desktop 
5133 | [429](https://httpstatuses.com/429) | https://github.com/qbittorrent/qBittorrent 
5147 | [429](https://httpstatuses.com/429) | https://github.com/timonus/Rhea 
5161 | [429](https://httpstatuses.com/429) | https://github.com/transmission/transmission 
5176 | [429](https://httpstatuses.com/429) | https://github.com/Tribler/tribler 
5190 | [429](https://httpstatuses.com/429) | https://github.com/vitorgalvao/appear.in 
5204 | [429](https://httpstatuses.com/429) | https://github.com/sindresorhus/caprine#features 
5219 | [429](https://httpstatuses.com/429) | https://github.com/danielbuechele/goofy 
5233 | [429](https://httpstatuses.com/429) | https://github.com/Swiftodon/Leviathan 
5247 | [429](https://httpstatuses.com/429) | https://github.com/rsms/fb-mac-messenger 
5263 | [429](https://httpstatuses.com/429) | https://github.com/producthunt/producthunt-osx 
5277 | [429](https://httpstatuses.com/429) | https://github.com/1000ch/quail 
5293 | [429](https://httpstatuses.com/429) | https://github.com/terkelg/ramme 
5308 | [429](https://httpstatuses.com/429) | https://github.com/KeliCheng/Simpo 
5325 | [429](https://httpstatuses.com/429) | https://github.com/michealparks/galeri 
5339 | [429](https://httpstatuses.com/429) | https://github.com/obsproject/obs-studio 
5353 | [429](https://httpstatuses.com/429) | https://github.com/raphaelhanneken/apple-juice 
5371 | [429](https://httpstatuses.com/429) | https://github.com/AppPolice/AppPolice 
5391 | [429](https://httpstatuses.com/429) | https://github.com/Kevin-De-Koninck/Clean-Me 
5407 | [429](https://httpstatuses.com/429) | https://github.com/macmade/Diagnostics 
5423 | [429](https://httpstatuses.com/429) | https://github.com/Eun/DisableMonitor 
5437 | [429](https://httpstatuses.com/429) | https://github.com/etresoft/EtreCheck 
5451 | [429](https://httpstatuses.com/429) | https://github.com/DanielStormApps/Fanny 
5467 | [429](https://httpstatuses.com/429) | https://github.com/jwise/HoRNDIS 
5481 | [429](https://httpstatuses.com/429) | https://github.com/brianmichel/Juice 
5498 | [429](https://httpstatuses.com/429) | https://github.com/newmarcel/KeepingYouAwake 
5514 | [429](https://httpstatuses.com/429) | https://github.com/mangerlahn/Latest 
5530 | [429](https://httpstatuses.com/429) | https://github.com/BonzaiThePenguin/Loading 
5546 | [429](https://httpstatuses.com/429) | https://github.com/KrauseFx/overkill-for-mac 
5560 | [429](https://httpstatuses.com/429) | https://github.com/ProfileCreator/ProfileCreator 
5576 | [429](https://httpstatuses.com/429) | https://github.com/sveinbjornt/Sloth 
5594 | [429](https://httpstatuses.com/429) | https://github.com/rugarciap/Turbo-Boost-Switcher 
5608 | [429](https://httpstatuses.com/429) | https://github.com/DeromirNeves/VerticalBar 
5624 | [429](https://httpstatuses.com/429) | https://github.com/alacritty/alacritty 
5640 | [429](https://httpstatuses.com/429) | https://github.com/ishuah/bifrost 
5654 | [429](https://httpstatuses.com/429) | https://github.com/macmade/Console 
5670 | [429](https://httpstatuses.com/429) | https://github.com/zeit/hyper 
5687 | [429](https://httpstatuses.com/429) | https://github.com/gnachman/iTerm2 
5701 | [429](https://httpstatuses.com/429) | https://github.com/kovidgoyal/kitty 
5716 | [429](https://httpstatuses.com/429) | https://github.com/es-kumagai/OpenTerminal 
5730 | [429](https://httpstatuses.com/429) | https://github.com/railsware/upterm 
5754 | [429](https://httpstatuses.com/429) | https://github.com/mczachurski/wallpapper 
5768 | [429](https://httpstatuses.com/429) | https://github.com/mortenjust/androidtool-mac 
5788 | [429](https://httpstatuses.com/429) | https://github.com/beardedspice/beardedspice 
5802 | [429](https://httpstatuses.com/429) | https://github.com/buttercup/buttercup-desktop 
5818 | [429](https://httpstatuses.com/429) | https://github.com/mipstian/catch/ 
5832 | [429](https://httpstatuses.com/429) | https://github.com/ekreutz/CornerCal 
5848 | [429](https://httpstatuses.com/429) | https://github.com/HR/Crypter 
5867 | [429](https://httpstatuses.com/429) | https://github.com/josejuanqm/ECheck 
5881 | [429](https://httpstatuses.com/429) | https://github.com/zenangst/Gray 
5895 | [429](https://httpstatuses.com/429) | https://github.com/alessiomaffeis/iOScanX 
5913 | [429](https://httpstatuses.com/429) | https://github.com/wulkano/kap 
5927 | [429](https://httpstatuses.com/429) | https://github.com/keepassxreboot/keepassxc 
5941 | [429](https://httpstatuses.com/429) | https://github.com/keeweb/keeweb 
5955 | [429](https://httpstatuses.com/429) | https://github.com/vishaltelangre/Kyapchar 
5969 | [429](https://httpstatuses.com/429) | https://github.com/wvdk/Life-Calendar 
5987 | [429](https://httpstatuses.com/429) | https://github.com/alin23/lunar 
6002 | [429](https://httpstatuses.com/429) | https://github.com/MacPass/MacPass 
6018 | [429](https://httpstatuses.com/429) | https://github.com/dragstor/mac-sound-fix 
6034 | [429](https://httpstatuses.com/429) | https://github.com/shincurry/Maria 
6048 | [429](https://httpstatuses.com/429) | https://github.com/MemeMaker/Meme-Maker-Mac 
6062 | [429](https://httpstatuses.com/429) | https://github.com/IngmarStein/Monolingual 
6078 | [429](https://httpstatuses.com/429) | https://github.com/Caldis/Mos 
6092 | [429](https://httpstatuses.com/429) | https://github.com/jariz/Noti/ 
6106 | [429](https://httpstatuses.com/429) | https://github.com/padloc/padloc 
6120 | [429](https://httpstatuses.com/429) | https://github.com/bitwarden/desktop 
6138 | [429](https://httpstatuses.com/429) | https://github.com/sidneys/pb-for-desktop 
6157 | [429](https://httpstatuses.com/429) | https://github.com/cemolcay/PercentCalculator 
6171 | [429](https://httpstatuses.com/429) | https://github.com/maxogden/screencat 
6186 | [429](https://httpstatuses.com/429) | https://github.com/dteoh/SlowQuitApps 
6200 | [429](https://httpstatuses.com/429) | https://github.com/64characters/Telephone 
6215 | [429](https://httpstatuses.com/429) | https://github.com/blockstack/blockstack-browser 
6243 | [429](https://httpstatuses.com/429) | https://github.com/zenangst/ToTheTop 
6257 | [429](https://httpstatuses.com/429) | https://github.com/felixhageloh/uebersicht 
6271 | [429](https://httpstatuses.com/429) | https://github.com/yichengchen/clashX 
6285 | [429](https://httpstatuses.com/429) | https://github.com/riboseinc/cryptode-mac 
6299 | [429](https://httpstatuses.com/429) | https://github.com/shadowsocks/ShadowsocksX-NG 
6313 | [429](https://httpstatuses.com/429) | https://github.com/zhuhaow/Specht 
6329 | [429](https://httpstatuses.com/429) | https://github.com/zhuhaow/SpechtLite 
6343 | [429](https://httpstatuses.com/429) | https://github.com/Tunnelblick/Tunnelblick 
6357 | [429](https://httpstatuses.com/429) | https://github.com/lostjared/Acid.Cam.v2.OSX 
6371 | [429](https://httpstatuses.com/429) | https://github.com/insidegui/AppleEvents 
6385 | [429](https://httpstatuses.com/429) | https://github.com/maelswarm/Datamosh 
6401 | [429](https://httpstatuses.com/429) | https://github.com/xiaohk/FaceData 
6418 | [429](https://httpstatuses.com/429) | https://github.com/willamowius/gnugk 
6432 | [429](https://httpstatuses.com/429) | https://github.com/vdel26/gifted 
6446 | [429](https://httpstatuses.com/429) | https://github.com/videolan/vlc 
6460 | [429](https://httpstatuses.com/429) | https://github.com/HandBrake/HandBrake 
6474 | [429](https://httpstatuses.com/429) | https://github.com/edanchenkov/MenuTube 
6488 | [429](https://httpstatuses.com/429) | https://github.com/OpenShot/openshot-qt 
6502 | [429](https://httpstatuses.com/429) | https://github.com/Marginal/QLVideo 
6530 | [429](https://httpstatuses.com/429) | https://github.com/sahil-a/vidquizcreator 
6544 | [429](https://httpstatuses.com/429) | https://github.com/webtorrent/webtorrent-desktop 
6562 | [429](https://httpstatuses.com/429) | https://github.com/whoisandy/yoda 
6576 | [429](https://httpstatuses.com/429) | https://github.com/iina/iina 
6590 | [429](https://httpstatuses.com/429) | https://github.com/emoRaivis/MacMorpheus 
6606 | [429](https://httpstatuses.com/429) | https://github.com/lettier/movie-monad 
6623 | [429](https://httpstatuses.com/429) | https://github.com/niltsh/MPlayerX 
6637 | [429](https://httpstatuses.com/429) | https://github.com/mpv-player/mpv 
6651 | [429](https://httpstatuses.com/429) | https://github.com/gielcobben/caption 
6667 | [429](https://httpstatuses.com/429) | https://github.com/Kevin-De-Koninck/Sub-It 
6681 | [429](https://httpstatuses.com/429) | https://github.com/spilja/Subtitlr/tree/master 
6695 | [429](https://httpstatuses.com/429) | https://github.com/cuddlecheek/500-mac-wallpaper 
6709 | [429](https://httpstatuses.com/429) | https://github.com/NghiaTranUIT/artify-macos 
6728 | [429](https://httpstatuses.com/429) | https://github.com/JustinFincher/ASWP-for-macOS 
6742 | [429](https://httpstatuses.com/429) | https://github.com/pengsrc/BingPaper 
6759 | [429](https://httpstatuses.com/429) | https://github.com/VioletGiraffe/desktop-wallpaper-switcher 
6773 | [429](https://httpstatuses.com/429) | https://github.com/viatsko/earth-wallpapers 
6787 | [429](https://httpstatuses.com/429) | https://github.com/IngoHeimbach/pyDailyChanger 
6801 | [429](https://httpstatuses.com/429) | https://github.com/naman14/Muzei-macOS 
6815 | [429](https://httpstatuses.com/429) | https://github.com/tomtaylor/satellite-eyes 
6831 | [429](https://httpstatuses.com/429) | https://github.com/davidcelis/Sunscreen 
6847 | [429](https://httpstatuses.com/429) | https://github.com/diogosantos/WallpaperMenu 
6861 | [429](https://httpstatuses.com/429) | https://github.com/ianyh/Amethyst 
6879 | [429](https://httpstatuses.com/429) | https://github.com/mjolnirapp/AppGrid 
6896 | [429](https://httpstatuses.com/429) | https://github.com/mamiksik/Desktop-Profiles 
6913 | [429](https://httpstatuses.com/429) | https://github.com/koekeishiya/chunkwm 
6927 | [429](https://httpstatuses.com/429) | https://github.com/Hammerspoon/hammerspoon 
6942 | [429](https://httpstatuses.com/429) | https://github.com/kasper/phoenix 
6958 | [429](https://httpstatuses.com/429) | https://github.com/fikovnik/ShiftIt 
6976 | [429](https://httpstatuses.com/429) | https://github.com/jigish/slate 
6990 | [429](https://httpstatuses.com/429) | https://github.com/eczarny/spectacle 
7004 | [429](https://httpstatuses.com/429) | https://github.com/klaaspieter/letters 
7023 | [429](https://httpstatuses.com/429) | https://github.com/thecatalinstan/Funky 
7037 | [429](https://httpstatuses.com/429) | https://github.com/subethaedit/SubEthaEdit 
7054 | [429](https://httpstatuses.com/429) | https://github.com/zagahr/Conferences.digital 
7070 | [429](https://httpstatuses.com/429) | https://github.com/vladimiry/ElectronMail 
7087 | [429](https://httpstatuses.com/429) | https://github.com/luin/medis 
7103 | [429](https://httpstatuses.com/429) | https://github.com/lessmess-dev/touch-emoji 
7116 | [429](https://httpstatuses.com/429) | https://github.com/LumingYin/ClipboardClear 
7137 | [429](https://httpstatuses.com/429) | https://github.com/Ji4n1ng/OpenInTerminal 
7156 | [429](https://httpstatuses.com/429) | https://github.com/jbtule/cdto 
7170 | [429](https://httpstatuses.com/429) | https://github.com/sindresorhus/quick-look-plugins 
7194 | [429](https://httpstatuses.com/429) | https://github.com/pigigaldi/Pock 
7206 | [429](https://httpstatuses.com/429) | https://github.com/macmade/Notarize 
7222 | [429](https://httpstatuses.com/429) | https://github.com/vpeschenkov/Predator 
7239 | [429](https://httpstatuses.com/429) | https://github.com/amiantos/lifesaver 
7245 | [429](https://httpstatuses.com/429) | https://github.com/amiantos/lifesaver/blob/master/Design/tvos/tvos-ss-1.png 
7246 | [429](https://httpstatuses.com/429) | https://github.com/amiantos/lifesaver/blob/master/Design/tvos/tvos-ss-2.png 
7257 | [429](https://httpstatuses.com/429) | https://github.com/LumingYin/Caption 
7273 | [429](https://httpstatuses.com/429) | https://github.com/LumingYin/SpeedReader 
7278 | [429](https://httpstatuses.com/429) | https://github.com/LumingYin/SpeedReader/blob/master/speedreader_dark.gif 
7293 | [429](https://httpstatuses.com/429) | https://github.com/rxhanson/Rectangle 
7309 | [429](https://httpstatuses.com/429) | https://github.com/Mortennn/Dozer 
7325 | [429](https://httpstatuses.com/429) | https://github.com/audacity/audacity 
7347 | [429](https://httpstatuses.com/429) | https://github.com/doches/lilypond-ui 
7357 | [429](https://httpstatuses.com/429) | https://github.com/fphilipe/PageExtender.app 
7374 | [429](https://httpstatuses.com/429) | https://github.com/yonilevy/automute 
7391 | [429](https://httpstatuses.com/429) | https://github.com/ExistentialAudio/BlackHole 
7419 | [429](https://httpstatuses.com/429) | https://github.com/jhspetersson/fselect 
7433 | [429](https://httpstatuses.com/429) | https://github.com/livecode/livecode 
7447 | [429](https://httpstatuses.com/429) | https://github.com/ivoronin/TomatoBar 
7461 | [429](https://httpstatuses.com/429) | https://github.com/ivoronin/ArchiveMounter 
7475 | [429](https://httpstatuses.com/429) | https://github.com/nikolaeu/Numi 
7489 | [429](https://httpstatuses.com/429) | https://github.com/powershell/powershell 
7503 | [429](https://httpstatuses.com/429) | https://github.com/cryptomator/cryptomator 
7523 | [429](https://httpstatuses.com/429) | https://github.com/johannesjo/super-productivity 
7543 | [429](https://httpstatuses.com/429) | https://github.com/varol/Calculeta 
7558 | [429](https://httpstatuses.com/429) | https://github.com/khrykin/StrategrDesktop 
7576 | [429](https://httpstatuses.com/429) | https://github.com/jeromelebel/MongoHub-Mac 
7592 | [429](https://httpstatuses.com/429) | https://github.com/AlexPerathoner/Sessions 
7609 | [429](https://httpstatuses.com/429) | https://github.com/sindresorhus/Plash 
7626 | [429](https://httpstatuses.com/429) | https://github.com/kamranahmedse/pennywise 
7645 | [429](https://httpstatuses.com/429) | https://github.com/dnote/dnote 
7664 | [429](https://httpstatuses.com/429) | https://github.com/DaFuqtor/MiddleClick-Catalina 
7668 | [429](https://httpstatuses.com/429) | https://github.com/DaFuqtor/MiddleClick-Catalina/blob/master/demo.png 
7676 | [429](https://httpstatuses.com/429) | https://github.com/jet8a/pomodoro-cycle-app 
7677 | [429](https://httpstatuses.com/429) | https://github.com/jet8a/pomodoro-cycle-app/releases 
7697 | [429](https://httpstatuses.com/429) | https://github.com/emqx/MQTTX 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by skywinder** [comment]
Wrong branch. Now it’s fine

**Comment by serhii-londar** [comment]
@skywinder It's changing to Readme.md.

**Comment by skywinder** [comment]
@serhii-londar uups, my bad. fixed in #547

**Pull request closed without merging**
