### PR TITLE
add gSwitch

### PR DESCRIPTION
**Pull request by CodySchrank**
add gSwitch

## Project URL
https://github.com/CodySchrank/gSwitch

## Category
Menubar

## Description
gSwitch is intended to replace the functionality provided by gfxCardStatus since it is no longer maintained.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in alphabetical order
- [x] Appropriate language icon(s) added if applicable
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
@CodySchrank Thanks for your contribution! 👍 After removing it has conflicts. Can you fix it?

**Comment by CodySchrank** [comment]
Yeah looks like it just failed auto merge.

**Comment by kfjatuch** [comment]
pt., 19.10.2018, 00:15 użytkownik Cody Schrank <notifications@github.com>
napisał:

**Comment by serhii-londar** [comment]
@CodySchrank Conflict still not fixed))

**Pull request merged**
