### PR TITLE
Adding SwiftBar

### PR DESCRIPTION
**Pull request by melonamin**
## Project URL
https://github.com/swiftbar/SwiftBar

## Category
menubar

## Description
Powerful macOS menu bar customization tool
 
## Checklist

- [x] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x] Only one project/change is in this pull request
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1505 | [404](https://httpstatuses.com/404) | https://raw.githubusercontent.com/MitMaro/git-interactive-rebase-tool/master/docs/assets/images/git-interactive-rebase-demo.gif 
3772 | Error | https://joshparnham.com/projects/cloudytabs/CloudyTabs.png <br> Failed to open TCP connection to joshparnham.com:443 (getaddrinfo: nodename nor servname provided, or not known)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by melonamin** [comment]
@serhii-londar I'm not sure what is the process, build error triggered not by my changes

**Comment by serhii-londar** [comment]
@melonamin correct, no worries, I'll fix that.

**Comment by serhii-londar** [comment]
@melonamin Thank you! 👍

**Pull request merged**
