### PR TITLE
Add Speed Reader to the list of applications.

### PR DESCRIPTION
**Pull request by LumingYin**
## Project URL
https://github.com/LumingYin/SpeedReader

## Category
Productivity

## Description
Read faster with the power of silencing vocalization.
 
## Why it should be included to `Awesome macOS open source applications ` (optional)
The app has been downloaded by 1000+ users on the Mac App Store, and is featured by Natalia Nowak on [Mac360](https://mac360.com/2017/07/free-be-a-speed-reader-on-your-mac/).

## Checklist

- [x] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x] Only one project/change is in this pull request
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
@LumingYin Please fix conflicts.

**Comment by LumingYin** [comment]
> @LumingYin Please fix conflicts.
Fixed!

**Comment by LumingYin** [comment]
> @LumingYin Also please add empty icon URL. Example: "icon_url": ""

Added an empty icon URL.

**Comment by serhii-londar** [comment]
@LumingYin Thank you! 👍

**Pull request merged**
