### PR TITLE
Add the link to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by vpeschenkov**
Hello @serhii-londar, I'm not sure about this change or about how it should be. But what do you think about adding the link to the contributing guidelines to README?

### CODE REVIEW

**Comment by serhii-londar** [comment]
@vpeschenkov HI! Thank you for the suggestion, but in this case, this word means that you can contribute to listed repositories, not in current. I think it would be cool to add some sentence like 'If you have any suggestion then you can contribute to this repository' or something similar.

**Comment by vpeschenkov** [comment]
@serhii-londar Looks like my bad. Anyway, I want to suggest to remove the comma from that sentence, like "The main goal of this repository is to find free open source apps and start contributing" because we don't need the one there, and it was looking confusedly for me.

So, we can use the following sentences:
- If you have any suggestion then you can [contribute](CONTRIBUTING.md) to this repository!
- Please feel free to add an app to this list, but first, take a quick look at [the contributing guidelines](CONTRIBUTING.md)!
- Feel free to [contribute](CONTRIBUTING.md) to the list, any suggestions are welcome!
- Feel free to let us know your thoughts about the list. To add an app, please read [the contributing guidelines](CONTRIBUTING.md)!

Let me know which sentence seems fine to you?

**Comment by serhii-londar** [comment]
@vpeschenkov Agree with you 👍 Let's remove it.

Feel free to contribute to the list, any suggestions are welcome! - This one looks good for me! 👍

**Comment by vpeschenkov** [comment]
@serhii-londar done, let me know if something is wrong

**Comment by serhii-londar** [comment]
@vpeschenkov Great! Nice work! 👍 Thank you!

**Pull request merged**
