### PR TITLE
Added Quickwords

### PR DESCRIPTION
**Pull request by DCzajkowski**
## Project URL
https://github.com/quickwords/quickwords

## Category
**EDIT:** Productivity

## Description
Added Quickwords, a new, open-source productivity app, that helps you execute tedious tasks very quickly.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Appropriate language icon(s) added if applicable
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
@DCzajkowski Maybe it will be better to add it to Productivity category?

**Comment by DCzajkowski** [comment]
Sure! I must have missed it 😅

**Comment by serhii-londar** [comment]
Thank you! Nice work!

**Comment by DCzajkowski** [comment]
Thank you 😊

**Pull request merged**
