### PR TITLE
Add Rack

### PR DESCRIPTION
**Pull request by gentlemanhog**
## Project URL
https://github.com/VCVRack/Rack

## Category
Audio

## Description
Open-source virtual modular synthesiser.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in alphabetical order
- [x] Appropriate language icon(s) added if applicable
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
@gentlemanhog Please add it in alphabetical order.

**Comment by serhii-londar** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by gentlemanhog** [comment]
Apologies. I've sorted alphabetically now. Thanks.

**Comment by serhii-londar** [comment]
@gentlemanhog Thank you! 👍

**Pull request merged**
