### PR TITLE
Added AltTab

### PR DESCRIPTION
**Pull request by adarshvadwitiya**
Added [AltTab](https://github.com/lwouis/alt-tab-macos)

## Project URL
https://github.com/lwouis/alt-tab-macos

## Category
Window Management

## Description
**AltTab** brings the power of Windows alt-tab to macOS
 
## Why it should be included to `Awesome macOS open source applications ` (optional)
This application is very handy for developers, is open source, and is actively being updated

## Checklist

- [x] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x] Only one project/change is in this pull request
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lwouis** [comment]
Hi @adarshv90 

I just realized today that i opened a PR for AltTab, but you already had opened one. I checked the issues before opening, but didn't think to check open PRs.

I looked at the code changes in your PR, and I believe there are some issues. The icon URL is a dynamic URL which will expire after the website is updated; the category could be expanded; etc.

I suggest you could close this PR and we could roll with mine here: https://github.com/serhii-londar/open-source-mac-os-apps/pull/681

Of course it's just a suggestion. Please check out my code changes and compare with this PR to make your mind.

Thank you for taking time to open a PR in any case! It's great to see people enjoying the app 😌

**Comment by serhii-londar** [comment]
@adarshvadwitiya Thank you!

**Comment by lwouis** [comment]
@serhii-londar could you check my comment above? I'm afraid there were 2 PRs for this app 😅

**Comment by serhii-londar** [comment]
@adarshvadwitiya Yes, I see now duplication in readme file) I'll fix that, thanks.

**Pull request merged**
