### PR TITLE
Add Nocturnal

### PR DESCRIPTION
**Pull request by joshjon**
## Project URL
https://github.com/joshjon/nocturnal

## Category

- `utilities`
- `menubar`

## Description
Nocturnal is an open-source app that is great for people who have sensitive eyes. It lets you apply darker than dark dimming, fine tune Night Shift temperature, completely turn off TouchBar on Macbook Pro, and supports multi-screen setups.
 
## Checklist

- [x] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x] Only one project/change is in this pull request
- [x] Screenshots(s) added if any
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
4761 | Error | https://github.com/shubhambatra3019/macOrganizer <br> Failed to open TCP connection to github.com:443 (Operation timed out - connect(2) for "github.com" port 443)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by serhii-londar** [comment]
@joshjon Thank you! 👍

**Comment by rasulkireev** [comment]
I get the "Nocturnal will damage you computer". Is it only me?

image

**Comment by joshjon** [comment]
> I get the "Nocturnal will damage you computer". Is it only me?

I can see you have installed Nocturnal using homebrew. Can you please double check that you have installed the cask joshjon-nocturnal. There is a pre-existing cask called nocturnal that is a completely different app which is no longer supported. I had another user report the same issue but it turns out they just installed the incorrect cask.

**Comment by rasulkireev** [comment]
Thanks @joshjon !

**Pull request merged**
