### PR TITLE
add GokuRakuJoudo, karabiner configuration manager

### PR DESCRIPTION
**Pull request by yqrashawn**
Add GokuRakuJoudo, the project is written in clojure. There's no icon for clojure in this repo, should I add it?

## Project URL
https://github.com/yqrashawn/GokuRakuJoudo

## Category
Keyboard

## Description
It substitute karabiner.json with karabiner.edn, let user manage their config at ease.
 
## Why it should be included to `Awesome macOS open source applications ` (optional)
My karabiner.json is more than 5000 lines. And this make it less than 300.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in alphabetical order
- [x] Appropriate language icon(s) added if applicable
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by serhii-londar** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
141 | Dupe | https://matrix.org/blog/home/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by serhii-londar** [comment]
@yqrashawn Yes, please add icon.

**Comment by yqrashawn** [comment]
@serhii-londar Thats done.

**Comment by serhii-londar** [comment]
@yqrashawn Thanks for your contribution! 👍

**Pull request merged**
